# Generated by Django 4.2.7 on 2023-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0002_airport_alter_flight_destination_alter_flight_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="city",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="airport",
            name="code",
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
